transform:
  global_crops_scale: [0.14, 1.0]
  local_crops_scale: [0.05, 0.14]
  local_crops_number: 6

train:
  batch_size_per_gpu: 64
  lr: 0.3
  min_lr: 0.0048
  warmup_epochs: 10
  weight_decay: 0.000001
  weight_decay_end: 0.000001
  warmup_teacher_temp: 0.04
  clip_grad: null
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 10
  student_temp: 0.1
  center_momentum: 0.9
  momentum_teacher: 0.996
  n_epochs: 20

architecture:
  output_dim: 60000
  use_bn_in_head: True
  norm_last_layer: True
  model_name: resnet18