transform:
  global_crops_scale: [0.25, 1.0]
  local_crops_scale: [0.05, 0.25]
  local_crops_number: 10

train:
  batch_size_per_gpu: 128
  accumulate_grad_batches: 1
  lr: 0.001
  min_lr: 0.00001
  warmup_epochs: 10
  weight_decay: 0.04
  weight_decay_end: 0.4
  warmup_teacher_temp: 0.04
  clip_grad: null
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
  student_temp: 0.1
  center_momentum: 0.9
  momentum_teacher: 0.996
  n_epochs: 10
  n_model_epochs: 800
  freeze_last_layer: 1

architecture:
  output_dim: 65536
  use_bn_in_head: false
  norm_last_layer: true
  model_name: vit_small
  patch_size: 16
  drop_path_rate: 0.1
