defaults:
  - model: resnet18

seed: 42

machine:
  num_workers: 8
  num_gpus: 8
  num_nodes: 1
  precision: "f16-true"

paths:
  model_checkpoint: checkpoints/
  data_path: data/gldv2/index/
  resume_from_checkpoint: null
