defaults:
  - model: vit_small
  - _self_

seed: 42
compile_model: true

machine:
  num_workers: 32
  num_gpus: 8
  num_nodes: 1
  precision: "bf16-true"

paths:
  model_checkpoint: checkpoints/
  data_path: data/gldv2/index/
  resume_from_checkpoint: null
